### ISSUE TITLE
Using a configurable "TF_*" by cmake. and Thanks!

### ISSUE THREAD

**Issue by danieagle** [lynxlynx/tfcipher#3]
Hi!

How you prefer, programaticaly, choose TF_* for use in tfdeh.h ?

I create a proposal in [https://github.com/danieagle/tfcipher/tree/tf_bit_choose](url)

More Ideas are wellcome !

And Very Very Very Thanks!

Best whishes,
Daniel.

-----x----
tfdef.h
to choose: 
/* config block */
#define TF_256BITS
/* #define TF_512BITS */
/* #define TF_1024BITS */
/* #define TF_NO_ENDIAN */
/* #define TF_BIG_ENDIAN */

**Comment by strlcat** [comment]
Since this code is a library, I prefer to define these settings in makefile or project header file.

**Comment by danieagle** [comment]
Hi!

You can elaborate an example?

Thanks!

Best whishes,
Daniel.

Em dom, 19 de dez de 2021 20:54, Andrey Rys ***@***.***>
escreveu:

**Comment by strlcat** [comment]
`cc -O3 -DTF_256BITS -I. -c tfenc.c` in your project Makefile.

**Comment by danieagle** [comment]
Hi!
Thanks

The installed headers need known these choosed parameter for the installed
library.

You can try compile and install using cmake and
create a cmake makefile with:
Import/search libs tfchifer tfchifer_supp
And add a exec.

This Will need the exactly compilable value used in -D
But this value dont are disponible anymore.

We Will search for a mode to perenize this value in -D in an installed
cmake makefile.

I Will report when get some success 👍

Best whishes,
Daniel.




Em dom, 19 de dez de 2021 21:30, Andrey Rys ***@***.***>
escreveu:
